# Generated by Django 6.0.4 on 2026-04-14 17:39

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='actor',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='genre',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
