# Generated by Django 6.0.4 on 2026-04-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_actor_managers_alter_genre_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='actor',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='genre',
            managers=[
            ],
        ),
    ]
